### ISSUE TITLE
Can not compile example_ofxTimeStretching

### ISSUE THREAD

**Issue by elliotjpb** [d3cod3/ofxTimeStretching#1]
I have tried to compile example_ofxTimeStretching on Mac OS and on Linux. I haven't successfully got it to compile on either. I have these errors:

`Undefined symbols for architecture x86_64:
  "RubberBand::RubberBandStretcher::RubberBandStretcher(unsigned long, unsigned long, int, double, double)", referenced from:
      ofxTimeStretching::setup(int, int) in ofxTimeStretching.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

There are also various undefined references to a few of the Ruberband functions when attempting to compile for linux

```
../../../addons/obj/linuxarmv6l/Release/ofxTimeStretching/src/ofxTimeStretching.o: In function `ofxTimeStretching::setup(int, int)':
ofxTimeStretching.cpp:(.text+0x34): undefined reference to `RubberBand::RubberBandStretcher::RubberBandStretcher(unsigned int, unsigned int, int, double, double)'
../../../addons/obj/linuxarmv6l/Release/ofxTimeStretching/src/ofxTimeStretching.o: In function `ofxTimeStretching::setTimeRatio(double)':
ofxTimeStretching.cpp:(.text+0x60): undefined reference to `RubberBand::RubberBandStretcher::setTimeRatio(double)'
../../../addons/obj/linuxarmv6l/Release/ofxTimeStretching/src/ofxTimeStretching.o: In function `ofxTimeStretching::setPitchScale(double)':
ofxTimeStretching.cpp:(.text+0x68): undefined reference to `RubberBand::RubberBandStretcher::setPitchScale(double)'
collect2: error: ld returned 1 exit status
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:382: recipe for target 'bin/example_ofxTimeStretching' failed
```

Has this been successfully compiled?

**Comment by d3cod3** [comment]
Hey, sorry but this addon is actually not ready for use nor compiling.
I'll let you know when it will be!

**Comment by elliotjpb** [comment]
I see! Thanks for your reply.
